# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  disableForcePushing: true

gui:
  showRandomTip: false
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 6
  commandLogSize: 4
