# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """\
( $username$hostname )(${directory} )${env_var.PROMPT_VCS_STATUS}$line_break\
$character\
"""

right_format = """
( ${env_var.DEBUG_CMD_HOOK})\
( $shlvl)\
( $singularity)\
( $vcsh)\
( $fossil_branch)\
( $fossil_metrics)\
( $hg_branch)\
( $pijul_channel)\
( $kubernetes)\
( $docker_context)\
( $package)\
( $c)\
( $cmake)\
( $cobol)\
( $daml)\
( $dart)\
( $deno)\
( $dotnet)\
( $elixir)\
( $elm)\
( $erlang)\
( $fennel)\
( $gleam)\
( $golang)\
( $guix_shell)\
( $haskell)\
( $haxe)\
( $helm)\
( $java)\
( $julia)\
( $kotlin)\
( $gradle)\
( $lua)\
( $nim)\
( $nodejs)\
( $ocaml)\
( $opa)\
( $perl)\
( $php)\
( $pulumi)\
( $purescript)\
( $python)\
( $quarto)\
( $raku)\
( $rlang)\
( $red)\
( $ruby)\
( $rust)\
( $scala)\
( $solidity)\
( $swift)\
( $terraform)\
( $typst)\
( $vlang)\
( $vagrant)\
( $zig)\
( $buf)\
( $nix_shell)\
( $conda)\
( $meson)\
( $spack)\
( $memory_usage)\
( $aws)\
( $gcloud)\
( $openstack)\
( $azure)\
( $nats)\
( $direnv)\
( $crystal)\
( $sudo)\
( $cmd_duration)\
( $jobs)\
( $status)\
"""

# [character]
#success_symbol = "[❯](purple)"
#error_symbol = "[❯](red)"
#vimcmd_symbol = "[❮](green)"

[env_var.DEBUG_CMD_HOOK]
disabled = true
variable = "__hook_cmd_kubectl"
format = "([$env_value]())"

[env_var.PROMPT_VCS_STATUS]
variable = "PROMPT_VCS_STATUS"
format = "([$env_value]())"

[env_var.PWD]
variable = "PWD"
format = "[$env_value]($style) "
style = '39'

[git_branch]
disabled = true
format = "[$branch]($style) "
style = "bright-black"

[git_status]
disabled = true
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)"
# format = "> ${staged}"
style = "cyan"
ignore_submodules = true

conflicted = '~${count} '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇡${ahead_count}⇣${behind_count}'
up_to_date = ''
untracked = '?${count} '
stashed = '*${count} '
modified = '!${count} '
staged = '+${count} '
renamed = 'R${count} '
deleted = 'D${count} '
#
[git_state]
disabled = true
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[username]
disabled = false
style_user = '033'
style_root = 'black bold'
format = '[$user]($style)'
show_always = true


[hostname]
disabled = false
ssh_only = false
format = '[@$hostname]($style)'
style = '033'

[directory]
read_only = '∅'
format = '([$read_only]($read_only_style) )[$path]($style)'
truncation_length = 3
truncation_symbol = '../'
truncate_to_repo = false
style = '39'

# 
# Plugins
# 
[golang]
format = "[($symbol($version))]($style)"

[nodejs]
format = "[($symbol($version))]($style)"

[kubernetes]
disabled = false
symbol = "󱃾 "
format = "[($symbol$context(($namespace)))]($style)"
detect_env_vars = [
    "KUBECONFIG"
]
# detect_env_vars = [
#     "__hook_cmd_kubectl",
#     "__hook_cmd_helm",
#     "__hook_cmd_kubens",
#     "__hook_cmd_kubectx",
#     "__hook_cmd_oc",
#     "__hook_cmd_istioctl",
#     "__hook_cmd_kogito",
#     "__hook_cmd_k9s",
#     "__hook_cmd_helmfile",
#     "__hook_cmd_flux",
#     "__hook_cmd_fluxctl",
#     "__hook_cmd_stern",
#     "__hook_cmd_kubeseal",
#     "__hook_cmd_skaffold",
#     "__hook_cmd_kubent",
#     "__hook_cmd_kubecolor",
#     "__hook_cmd_cmctl",
#     "__hook_cmd_sparkctl",
# ]
style = '39 bold'

[python]
format = "[($symbol($version))]($style)"
style = "bright-black"

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style) '
symbol = "G "
detect_env_vars = ["__hook_cmd_gcloud", "__hook_cmd_gcs", "__hook_cmd_gsutil"]
